#51 edit api requests
AlexKay28/langflow pull request #52
Opened 2021-11-04 12:25 UTC by Alkhimovmv

I changed the requests to match the backend. 
There is a hardcode here. When the database appears, I will remove it

2021-11-06 06:31 UTC, AlexKay28 commented
@Alkhimovmv

2021-11-06 06:33 UTC, AlexKay28 requested changes
answer asked questions in comments and add some changes in code (if its needed)

2021-11-06 06:33 UTC, AlexKay28 commented on frontend/src/components/GoPractice/GoPractice.tsx
> +        const session_token = '40b39433-f0a5-4d89-abf2-7649fdcf2e7b'
is this ok to store session_token in code? maybe you will move it out of code as temporal config for testing now... at least it definitely should be removed later

2021-11-06 06:33 UTC, AlexKay28 commented on frontend/src/components/GoPractice/GoPractice.tsx
> +        const session_token = '40b39433-f0a5-4d89-abf2-7649fdcf2e7b'
oh, i guess the commented code above is something what was replaced by this one) am I right?

2021-11-06 06:33 UTC, AlexKay28 commented on frontend/src/components/Question/Question.jsx
> +        const session_token = '40b39433-f0a5-4d89-abf2-7649fdcf2e7b'
yeah, i see it again... maybe its a good practice to put comments in code whose let others developers to know what's going on here

2021-11-06 06:33 UTC, AlexKay28 commented on frontend/src/components/Question/Question.jsx
> +        const session_token = '40b39433-f0a5-4d89-abf2-7649fdcf2e7b'
the same as above

2021-11-06 10:09 UTC, Alkhimovmv commented
> @Alkhimovmv if the interface has changed somehow, could you please attach screenshots in the comments please...

Yes, I moved the GoPractice component to the top and pinned it like we discussed
![Снимок экрана от 2021-11-06 13-03-48](https://user-images.githubusercontent.com/61086417/140605913-34604a7e-e4ff-41a5-afaa-34059fab0c45.png)
![Снимок экрана от 2021-11-06 13-04-06](https://user-images.githubusercontent.com/61086417/140605917-8867bc73-00f4-4a3e-b33b-8fac5aaf64c1.png)
![Снимок экрана от 2021-11-06 13-05-33](https://user-images.githubusercontent.com/61086417/140605919-6a36a0c1-f5da-47c2-825c-017cf668250b.png)

2021-11-06 10:14 UTC, Alkhimovmv commented on frontend/src/components/GoPractice/GoPractice.tsx
> +        const session_token = '40b39433-f0a5-4d89-abf2-7649fdcf2e7b'
Yes, you're right, the commented code above is something what was replaced by this one. But I see no reason to move the session_token to the config, if with the appearance of database I remove this line and uncomment the code

2021-11-06 10:16 UTC, Alkhimovmv commented on frontend/src/components/Question/Question.jsx
> +        const session_token = '40b39433-f0a5-4d89-abf2-7649fdcf2e7b'
Yes, it's better for understanding what's going on in this code.

2021-11-06 12:17 UTC, AlexKay28 commented
> > @Alkhimovmv if the interface has changed somehow, could you please attach screenshots in the comments please...
> 
> Yes, I moved the GoPractice component to the top and pinned it like we discussed ![Снимок экрана от 2021-11-06 13-03-48](https://user-images.githubusercontent.com/61086417/140605913-34604a7e-e4ff-41a5-afaa-34059fab0c45.png) ![Снимок экрана от 2021-11-06 13-04-06](https://user-images.githubusercontent.com/61086417/140605917-8867bc73-00f4-4a3e-b33b-8fac5aaf64c1.png) ![Снимок экрана от 2021-11-06 13-05-33](https://user-images.githubusercontent.com/61086417/140605919-6a36a0c1-f5da-47c2-825c-017cf668250b.png)

You good, I see!) nice answer

2021-11-06 12:18 UTC, AlexKay28 commented
ok, watch for #39

2021-11-09 20:22 UTC, alantishin approved these changes

2021-11-10 04:57 UTC, AlexKay28 approved these changes

2021-11-10 17:24 UTC, merged

2021-11-29 18:32 UTC, Alkhimovmv commented
![](https://github.trello.services/images/mini-trello-icon.png) [Handle new API](https://trello.com/c/vOSHBsKV/3-handle-new-api)